spring:
  profiles:
    include: default
  batch:
    initialize-schema: always
    job:
      enabled: false
    tablePrefix: BCX_OWNER.BATCH_
  datasource:
    driver-class: "oracle.jdbc.driver.OracleDriver"
    password: "SxNQWEa1"
    url: "jdbc:oracle:thin:@bil0stl25:1527:DBCXS"
    username: "bcx_user"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 10
    max-idle: 2
    max-wait: 8000
  jpa:
    hibernate:
      ddl-auto: none
tableName:
  GCMSBA: 'GCMS_TRANSACTION_DETAIL'
  GCMSBE: 'GCMS_BILLING_EVENT_DETAIL'
  AUTHBA: 'AUTH_TRANSACTION_DETAIL'
  AUTHBE: 'AUTH_BILLING_EVENT_DETAIL'
  DEBITBA: 'DEBIT_TRANSACTION_DETAIL'
  DEBITBE: 'DEBIT_BILLING_EVENT_DETAIL'
  BTID: 'BILLING_DETAIIL_TRACE_ID'
  QMRBA: 'QMR_TRANSACTION_DETAIL'
  QMRBE: 'QMR_BILLING_EVENT_DETAIL'
  
  batch:
  chunk:
    size: 10
file:
  regexIgnore:
    pattern: '.*temp.*|.*tmp.*'
  typeRegex:
    pattern: _
  tablePrefix:
    name: BCX_OWNER.
