spring:
  profiles:
    include: default
  batch:
    initialize-schema: always
    job:
      enabled: false
    tablePrefix: BCX_OWNER.BATCH_
tableName:
  GCMSBA: 'GCMS_TRANSACTION_DETAIL'
  GCMSBE: 'GCMS_BILLING_EVENT_DETAIL'
  AUTHBA: 'AUTH_TRANSACTION_DETAIL'
  AUTHBE: 'AUTH_BILLING_EVENT_DETAIL'
  DEBITBA: 'DEBIT_TRANSACTION_DETAIL'
  DEBITBE: 'DEBIT_BILLING_EVENT_DETAIL'
  BTID: 'BILLING_DETAIIL_TRACE_ID'
  QMRBA: 'QMR_TRANSACTION_DETAIL'
  QMRBE: 'QMR_BILLING_EVENT_DETAIL'
